### PR TITLE
Added ETag field for concurrency resolution on Set-CosmosDbDocument

### PR DESCRIPTION
**Pull request by minorai**
**Enhancement**
Currently there is now way to set If-Match header (or any other header) on Set-CosmosDbDocument command. This PR will allow user to set If-Match header so that update query will fail if someone has modified the document before us. Current ETag is fetched from the document by accessing $document._etag field.

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/cosmosdb/303)

### CODE REVIEW

**Comment by minorai** [comment]
Hello @PlagueHO 
Thank you!

I have updated the change log and the documentation. Tell me if you want to change anything!
I will add a unit test later this weekend.

Cheers!

**Comment by minorai** [comment]
I have added a couple of unit tests. I would like to add an integration test a bit later, once I set up the dev environment.

**Comment by PlagueHO** [comment]
Hi @minorai ! Thanks for making the changes! I'll review and get this merged in a couple of days (just a bit snowed under till the end of the weekend). I've raised an issue to fix the integration tests throwing an error in Azure DevOps when executed against a PR. So that will allow the PR to merge (although still not sure why some of the statuses haven't been reported - might just have to merge anyway. Sorry about the delay!

**Comment by PlagueHO** [comment]
Can you rebase @minorai and fix the conflicts? I made a change to resolve the PR build failure you were seeing (so that I can merge your change). Thank you!

**Comment by minorai** [comment]
@PlagueHO Done!

**Pull request merged**
