### PR TITLE
Replacing $Null by Out-Null

### PR DESCRIPTION
**Pull request by thomas-illiet**
This change is [Reviewable](https://reviewable.io/reviews/plagueho/cosmosdb/250)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @thomas-illiet - functionally I'm fine with this change, although I tend to use the higher performance `$null = Cmdlet` approach (the `[void](Cmdlet)` approach has the same performance). Ideally if we were to move over to the `Cmdlet | Out-Null` approach it would be better to do this across the whole module - I'm a big fan of Clean Code :grin:

So I'm happy to bring this PR in, but I'd suggest it also cover the entire module. However, if there is a problematic behaviour using $null in the PSakefile, let me know and put a comment in the code (otherwise it might get reverted in one of my regular refactoring sessions).

I'm not sure why the TravisCI is failing either - I've kicked it again and will do some checks if it fails. Looks like it is something to do with the AzureRM modules.

**Comment by PlagueHO** [comment]
I've raised an issue to get this resolved:

https://github.com/PlagueHO/CosmosDB/issues/251

It will need to get fixed before this can be merged. I suspect that changes have been made to the TravisCI build agents. I couldn't find any references to recent changes so I'll need to do some debugging. Strange that it all works fine on Azure DevOps pipelines on Linux and Mac.

**Comment by PlagueHO** [comment]
I've had to make some further changes to Dev as the 1.0.0.0 Az module was released and it highlighted I'd missed some substitutions. Should be fixed soon. Check #254.

**Comment by thomas-illiet** [comment]
I will create this PR this weekend, because I do not have time :neckbeard:

**Comment by PlagueHO** [comment]
No worries! Cheers for your contribution!

**Pull request closed without merging**
