### PR TITLE
Style-based Changes to README

### PR DESCRIPTION
**Pull request by potatoqualitee**
I have made some style-based changes to the README and divided the changes into two commits so they can be cherry-picked if desired. Perhaps you want to accept one change but not the other.

## Improvements / Enhancements

- Made README prettier and more aligned with the style guide which requests the use of splats.

It says to contact an administrator -- the only person I know is @PlagueHO so I'll ping him 💀

- - -
This change is [Reviewable](https://reviewable.io/reviews/PlagueHO/CosmosDB/471)

### CODE REVIEW

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Awesome! Thanks @potatoqualitee - good catch on the "contact an administrator" - I copied this from the DSC Resource kit many years back but must have forgotten to update it.

Can you please add an entry to the CHANGELOG.md file under a new section `## Changed`?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/PlagueHO/CosmosDB/471#-:-NRWIu5L1EP5vS3CIw6a:buk7b1d)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @potatoqualitee)

**Comment by PlagueHO** [comment]
Hi @potatoqualitee - would you be able to update the ChangeLog so I can merge this PR?

**Comment by potatoqualitee** [comment]
oops, yes, sorry ill put this back on my todo list

**Comment by potatoqualitee** [comment]
uh oh, need an assist :/

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/PlagueHO/CosmosDB/471#-:-NUp0ZPl0cDi7w5qdtYk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @potatoqualitee)

**Review by PlagueHO — APPROVED** [review]
The unit tests are failing because Ubuntu 18.04 Azure DevOps images are now deprecated. I'll just merge this and have raised an issue to fix - see #473.

> *[Reviewable](https://reviewable.io/reviews/PlagueHO/CosmosDB/471#-:-NUp0amv-xivWStx0pju:b-6qu7cw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @potatoqualitee)

**Pull request merged**
