### PR TITLE
Issue 120 - Added 'None' as a valid IndexingMode

### LINKED ISSUE #120: Allow IndexingMode = 'None'
When I try to provision an index with the indexing mode set to none, the New-CosmosDbCollectionIndexingPolicy function returns an error as this value does not exist in the ValidateSet.

### PR DESCRIPTION
**Pull request by smneal**
`@PlagueHO`

# Bug Fixes

- Fixes #120

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/cosmosdb/121)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Thank you very much @smneal for submitting this! Very much appreciated - I didn't even know about the None option until you raised this.

Could you make the following changes:
1. Add the new None option to the docs\New-CosmosDbCollectionIndexingPolicy.md -indexingMode parameter description so that it shows up in the help. You could use the text 'A collection that has a None index mode has no index associated with it. This is commonly used if Azure Cosmos DB is used as a key-value storage, and documents are accessed only by their ID property. ' from the MSFT docs.
2. Add an entry to the CHANGELOG.MD in the # Unreleased section describing the change and the link to the GitHub issue - feel free to also mention your name as a contributor (see how previous contributors have layed out the entries in the CHANGELOG.MD). This will get copied to the release notes next time this module is published.
3. It is probably going to be a good idea to add an integration test for this case in the `test\CosmosDB.integration.Tests.ps1` file to ensure this doesn't get regressed.

To do 3, I'd suggest adding a block like this:
```powershell
    Context 'Create a new collection using a None indexing policy' {
        It 'Should not throw an exception' {
            {
                $script:indexingPolicy = New-CosmosDbCollectionIndexingPolicy -Automatic $true -IndexingMode None

                $script:result = New-CosmosDbCollection `
                    -Context $script:testContext `
                    -Id $script:testCollection `
                    -OfferThroughput 400 `
                    -IndexingPolicy $script:indexingPolicyNone `
                    -Verbose
            } | Should -Not -Throw
        }

        It 'Should return expected object' {
            $script:result.Timestamp | Should -BeOfType [System.DateTime]
            $script:result.Etag | Should -BeOfType [System.String]
            $script:result.ResourceId | Should -BeOfType [System.String]
            $script:result.Uri | Should -BeOfType [System.String]
            $script:result.Conflicts | Should -BeOfType [System.String]
            $script:result.Documents | Should -BeOfType [System.String]
            $script:result.StoredProcedures | Should -BeOfType [System.String]
            $script:result.Triggers | Should -BeOfType [System.String]
            $script:result.UserDefinedFunctions | Should -BeOfType [System.String]
            $script:result.Id | Should -Be $script:testCollection
            $script:result.indexingPolicy.indexingMode | Should -Be 'None'
            $script:result.indexingPolicy.automatic | Should -Be $true
        }
    }

    Context 'Remove existing collection with a None indexing Policy' {
        It 'Should not throw an exception' {
            {
                $script:result = Remove-CosmosDbCollection -Context $script:testContext -Id $script:testCollection -Verbose
            } | Should -Not -Throw
        }
    }
```powershell

This should go just before the `Context 'Remove existing database' {` in the integration tests file.

Does this make sense? I'm not sure the above tests will pass though as I haven't tested it myself, so we might need some tweaking. But I think this will definitely be worthwhile as I'm trying to slowly build up the integration test suite to improve the over all quality of the module.
```


---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/plagueho/cosmosdb/121#-:-LFMEbcy2TJE7zma7SUW:b7njd2k)*

**Comment by smneal** [comment]
That's all done. I noticed the CosmosDB.integration.Tests.ps1 don't run on AppVeyor. I have run it locally and the new test goes through fine.

**Comment by PlagueHO** [comment]
Thanks @smneal - I'll finish review tonight after work and get this merged. The integration tests will run in AppVeyor, but only on master and on my PR's (it requires configuring the AppVeyor account to access my encrypted Azure creds). So it should run against master after I merge.

You can do the same thing (no need though) in your AppVeyor account and it'll then run the integration tests on your PR. But is not at all required - just an FYI as to how I set up AppVeyor:
image

**Comment by smneal** [comment]
That's great info. Thanks

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/plagueho/cosmosdb/121#-:-LFRQ0xV8RGBk_h1SFsZ:bnfp4nl)*

**Pull request merged**
