### PR TITLE
Refactor: PartitionKey to support int PartitionKeys

### PR DESCRIPTION
**Pull request by Splaxi**
## Improvements / Enhancements

- Refactor the PartionKey to support non-string keys

I'm unable to use the PlatyPS to generate the correct updated docs files for the New-CosmosDBDocument. Running the command from the CONTRIBUTING.md guide, simply generates markdown files with incorrect content.

@PlagueHO

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/cosmosdb/311)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @Splaxi - thanks again! Sorry for taking so long to review this - I'm sitting an Azure exam this weekend and so all my time has been taken with that. But I'll review as soon as I've done the exam (Saturday). I'll also re-kick the builds to see why they didn't report status.

**Comment by Splaxi** [comment]
No worries!

I hope you either find the quality to be high enough or simply get inspired to implement the support like you want it to be, so partitionkeys can integers as well as strings 😉

**Comment by PlagueHO** [comment]
Hi @Splaxi - sorry about the delay. I've just been fixing the CI/CD pipelines so that that the tests can pass in this PR. Once corrected, I'll get you to rebase onto Dev, which should allow your tests to pass.

**Comment by PlagueHO** [comment]
Hi @Splaxi - I have fixed the TravisCI build, so hopefully your PR will now pass.

**Comment by Splaxi** [comment]
I hope I did the right thing - the build is running 🤞

**Comment by PlagueHO** [comment]
Doh! No idea how that happened - I totally hadn't meant to merge it yet. Will revert and get you to resubmit.

**Comment by PlagueHO** [comment]
@Splaxi - can you recreate your PR? Completely sorry about that - I have no idea how the merge occurred...?

**Comment by PlagueHO** [comment]
Hi @Splaxi - regards this one, I've done a bit of refactoring and created a new function to deal with this to reduce code duplication and also provide some validation over the types. I'll submit this shortly. Sorry about the messing about!

**Comment by Splaxi** [comment]
Perfect! I happy that I could inspire you enough to add support for this request. Looking forward to the next release 🤘

**Comment by PlagueHO** [comment]
Thanks @Splaxi ! Awesome stuff - I've published this to the gallery as 3.5.1:
https://www.powershellgallery.com/packages/CosmosDB/3.5.1.458

**Pull request merged**
